output "cluster_id" {
  description = "EKS cluster ID."
  value       = module.eks.cluster_id
}

output "cluster_endpoint" {
  description = "Endpoint for EKS control plane."
  value       = module.eks.cluster_endpoint
}

output "cluster_certificate_authority" {
  description = "CA for EKS Cluster Endpoint"
  value       = data.aws_eks_cluster.cluster.certificate_authority.0.data
}

output "cluster_security_group_id" {
  description = "Security group ids attached to the cluster control plane."
  value       = module.eks.cluster_security_group_id
}

output "kubectl_config" {
  description = "kubectl config as generated by the module."
  value       = module.eks.kubeconfig
}

output "kubeconfig_filename" {
  description = "kubectl config filename as generated by the module."
  value       = module.eks.kubeconfig_filename
}

output "config_map_aws_auth" {
  description = "A kubernetes configuration to authenticate to this EKS cluster."
  value       = module.eks.config_map_aws_auth
}

output "cluster_name" {
  description = "Kubernetes Cluster Name"
  value       = local.cluster_name
}

output "eks" {
  description = "output from terraform-aws-module/eks/aws module"
  value       = module.eks
}

output "vpc_id" {
  description = "output from terraform-aws-modules/vpc/aws module"
  value       = module.vpc.vpc_id
}

output "vpc_public_subnet_ids" {
  description = "output from terraform-aws-modules/vpc/aws module"
  value       = module.vpc.public_subnets
}

output "vpc_private_subnet_ids" {
  description = "output from terraform-aws-modules/vpc/aws module"
  value       = module.vpc.private_subnets
}